-- MySQL Script generated by MySQL Workbench
-- Sat Dec 10 09:28:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Motorista` (
  `idMotorista` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NULL,
  `chn` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `tel` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `avaliacao` INT(1) NULL,
  `Motoristacol` VARCHAR(45) NULL,
  PRIMARY KEY (`idMotorista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passageiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passageiro` (
  `idPassageiro` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `tel` VARCHAR(45) NULL,
  `avaliacao` INT(1) NULL,
  PRIMARY KEY (`idPassageiro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carro` (
  `idCarro` INT NOT NULL AUTO_INCREMENT,
  `chassi` INT NULL,
  `placa` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `ano` YEAR NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idCarro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carro_has_Motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carro_has_Motorista` (
  `Carro_idCarro` INT NOT NULL,
  `Motorista_idMotorista` INT NOT NULL,
  PRIMARY KEY (`Carro_idCarro`, `Motorista_idMotorista`),
  CONSTRAINT `fk_Carro_has_Motorista_Carro`
    FOREIGN KEY (`Carro_idCarro`)
    REFERENCES `mydb`.`Carro` (`idCarro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carro_has_Motorista_Motorista1`
    FOREIGN KEY (`Motorista_idMotorista`)
    REFERENCES `mydb`.`Motorista` (`idMotorista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Local` (
  `idLocal` INT NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  PRIMARY KEY (`idLocal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Viagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Viagem` (
  `idViagem` INT UNSIGNED NOT NULL,
  `inicio` DATETIME NULL,
  `fim` DATETIME NULL,
  `Passageiro_idPassageiro` INT NOT NULL,
  `Carro_has_Motorista_Carro_idCarro` INT NOT NULL,
  `Carro_has_Motorista_Motorista_idMotorista` INT NOT NULL,
  `Origen_idLocal` INT NOT NULL,
  `Destino_idLocal` INT NOT NULL,
  PRIMARY KEY (`idViagem`),
  CONSTRAINT `fk_Viagem_Passageiro1`
    FOREIGN KEY (`Passageiro_idPassageiro`)
    REFERENCES `mydb`.`Passageiro` (`idPassageiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Viagem_Carro_has_Motorista1`
    FOREIGN KEY (`Carro_has_Motorista_Carro_idCarro` , `Carro_has_Motorista_Motorista_idMotorista`)
    REFERENCES `mydb`.`Carro_has_Motorista` (`Carro_idCarro` , `Motorista_idMotorista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Viagem_Destino1`
    FOREIGN KEY (`Origen_idLocal`)
    REFERENCES `mydb`.`Local` (`idLocal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Viagem_Destino2`
    FOREIGN KEY (`Destino_idLocal`)
    REFERENCES `mydb`.`Local` (`idLocal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
